version: "3.8"

services:

  redmine:
    image: "redmine:4.0"
    ports:
      - "3000:3000"
    environment:
      - REDMINE_DB_POSTGRES: db
      - REDMINE_DB_USERNAME: redmine
      - REDMINE_DB_PASSWORD: 0pass123
    depends_on:
      - db

  db:
    image: "postgres:13"
    environment:
      - POSTGRES_PASSWORD: 0pass123
      - POSTGRES_USER: redmine
      -  db-data:/var/lib/postgresql/data

volumes:
  db-data: